# Generated by Django 3.2.15 on 2022-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_add_candidate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=18, max_length=3),
            preserve_default=False,
        ),
    ]
