# Generated by Django 3.2.15 on 2022-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_add_age_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
