# Generated by Django 3.2.15 on 2022-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_add_phone_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
