# Generated by Django 3.2.15 on 2022-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_Add_card2_and_card3_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(blank=True, upload_to='resume', verbose_name='Resume'),
        ),
    ]
