# Generated by Django 3.2.15 on 2022-09-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_Add_image_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='started_jon',
            new_name='started_job',
        ),
    ]
